import Head from "next/head";
import CallbackComponent from "../components/Profile/CallbackComponent";
import styles from "../styles/Home.module.css";

export default function callback() {
  return (
    <>
      <Head>
        <title>Greple Github Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
       <CallbackComponent></CallbackComponent>
      </main>
    </>
  );
}