import Redirect from "../components/Profile/Redirect";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";


export default function Meet() {
  return (
     
    <>
      <Head>
        <title>Greple Github Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Redirect></Redirect>
    </>
  );
}
